const keyboards = [{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: ['red','blue','brown'],
    imgs: ['../../../imgs/DataKeyboard/Akko/1/1.jpg']
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
},{
    id: 1,
    name: "test",
    price: 10000,
    brand: "logitech",
    wires: "Bluetooth",
    led: "RGB",
    color: "black",
    switches: "red",
    imgs: []
}];

export {keyboards}
export const accounts = [{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
},{
    username: "lnhau",
    password: "1234",
    owner : "hau",
    address: "quan 7 tp hcm",
    phone: "0965026920",
    email:"lnhau94@gmail.com",
}]